openapi: 3.0.0
info:
  title: Income Tracker API
  version: 1.0.0
  description: API pour gérer l'authentification et les revenus des utilisateurs.
servers:
  - url: http://localhost:8080/api

paths:
  /auth/sign:
    post:
      summary: Créer un compte utilisateur
      tags: 
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                  example: testtest@gmail.com
                password:
                  type: string
                  minLength: 6
                  maxLength: 64
                  example: "123456"
      responses:
        "201":
          description: Utilisateur créé avec succès
        "400":
          description: Requête invalide (données manquantes ou incorrectes)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "409":
          description: Conflit (email déjà utilisé)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "500":
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /auth/login:
    post:
      summary: Connexion d'un utilisateur
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                  example: testtest@gmail.com
                password:
                  type: string
                  example: "123456"
      responses:
        "200":
          description: Authentification réussie (retourne un token JWT)
        "400":
          description: Mauvaise requête (format incorrect)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "401":
          description: Identifiants invalides
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "500":
          description: Erreur serveur

  /income:
    post:
      summary: Créer un revenu
      security:
        - bearerAuth: []
      tags:
        - Income
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [amount, date, source]
              properties:
                amount:
                  type: number
                  minimum: 0
                  example: 1500
                date:
                  type: string
                  format: date
                  example: 2025-08-19
                source:
                  type: string
                  minLength: 2
                  maxLength: 100
                  example: Freelance
                description:
                  type: string
                  maxLength: 255
                  example: Projet X
      responses:
        "201":
          description: Revenu créé avec succès
        "400":
          description: Requête invalide
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "401":
          description: Non autorisé
        "422":
          description: Erreur de validation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

    get:
      summary: Lister tous les revenus de l’utilisateur
      security:
        - bearerAuth: []
      tags:
        - Income
      responses:
        "200":
          description: Liste des revenus
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Income"
        "401":
          description: Non autorisé
        "500":
          description: Erreur serveur

  /income/{id}:
    get:
      summary: Obtenir un revenu par ID
      security:
        - bearerAuth: []
      tags:
        - Income
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Revenu trouvé
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Income"
        "404":
          description: Revenu non trouvé
        "400":
          description: ID invalide
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
        "401":
          description: Non autorisé

    put:
      summary: Mettre à jour un revenu
      security:
        - bearerAuth: []
      tags:
        - Income
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  minimum: 0
                  example: 2000
                description:
                  type: string
                  maxLength: 255
                  example: Projet X mis à jour
      responses:
        "200":
          description: Revenu mis à jour
        "400":
          description: Requête invalide
        "404":
          description: Revenu non trouvé
        "401":
          description: Non autorisé

    delete:
      summary: Supprimer un revenu
      security:
        - bearerAuth: []
      tags:
        - Income
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Revenu supprimé avec succès
        "404":
          description: Revenu non trouvé
        "401":
          description: Non autorisé
        "400":
          description: ID invalide

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Income:
      type: object
      properties:
        id:
          type: string
          format: uuid
        amount:
          type: number
          example: 1500
        income_date:
          type: string
          format: date
          example: 2025-08-19
        source:
          type: string
          example: Freelance
        description:
          type: string
          example: Projet X

    ErrorMessage:
      type: object
      properties:
        message:
          type: string
          example: "Une erreur est survenue"
        error:
          type: string
          example: "Bad Request"
