version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "king aff"
      POSTGRES_DB: sequelizedb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    command: npm run dev   
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "3000:3000"       
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: "king aff"
      DB_NAME: sequelizedb
    depends_on:
      - db

volumes:
  db_data:
